"""Hardcoded Barcelona travel recommendations for /travel."""

from __future__ import annotations

import logging
import os
from typing import Any

import requests

logger = logging.getLogger(__name__)

UB_LAT = 41.3874
UB_LNG = 2.1686

TRAVEL_RECOMMENDATIONS_SEED: list[dict[str, Any]] = [
    # HUNGRY - Restaurants, Cafes, Markets, Food Halls (18 places)
    {
        "id": "boqueria",
        "name": "La Boqueria Market",
        "name_es": "Mercado de La Boqueria",
        "lat": 41.3819,
        "lng": 2.1715,
        "address": "La Rambla, 91, Ciutat Vella",
        "description_es": "Mercado emblemático junto a la Rambla: fruta, pescado y tapas. Ideal para practicar español con los puestos.",
        "description_en": "Iconic market off La Rambla: fruit, fish, and tapas. Great for practicing Spanish with vendors.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=La+Boqueria+Barcelona",
        "travel_time_ub": "12 min a pie desde UB",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["hungry", "cultural"],
    },
    {
        "id": "gracia-tapas",
        "name": "Gràcia neighborhood",
        "name_es": "Barrio de Gràcia",
        "lat": 41.4036,
        "lng": 2.1564,
        "address": "Gràcia, Barcelona",
        "description_es": "Plazas pequeñas, bares y ambiente local lejos del centro turístico.",
        "description_en": "Small squares, bars, and local vibe away from tourist center.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Gracia+Barcelona",
        "travel_time_ub": "15 min en metro (L3)",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["hungry", "chill", "cultural"],
    },
    {
        "id": "mercat-santa-caterina",
        "name": "Mercat de Santa Caterina",
        "name_es": "Mercado de Santa Caterina",
        "lat": 41.3847,
        "lng": 2.1760,
        "address": "Av. de Francesc Cambó, 16, El Born",
        "description_es": "Mercado modernizado con techo ondulado de colores. Tapas frescas y ambiente local.",
        "description_en": "Modernized market with colorful wavy roof. Fresh tapas and local atmosphere.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Mercat+Santa+Caterina+Barcelona",
        "travel_time_ub": "18 min en metro o bici",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["hungry", "cultural"],
    },
    {
        "id": "cerveceria-catalana",
        "name": "Cervecería Catalana",
        "name_es": "Cervecería Catalana",
        "lat": 41.3918,
        "lng": 2.1602,
        "address": "Carrer de Mallorca, 236, Eixample",
        "description_es": "Bar de tapas popular. Prueba jamón ibérico, patatas bravas y vermut.",
        "description_en": "Popular tapas bar. Try Iberian ham, patatas bravas, and vermouth.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cerveceria+Catalana+Barcelona",
        "travel_time_ub": "10 min a pie desde UB",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry"],
    },
    {
        "id": "quimet-quimet",
        "name": "Quimet & Quimet",
        "name_es": "Quimet & Quimet",
        "lat": 41.3751,
        "lng": 2.1661,
        "address": "Carrer del Poeta Cabanyes, 25, Poble Sec",
        "description_es": "Bar de montaditos diminuto y famoso. Llega temprano para conseguir sitio.",
        "description_en": "Tiny, famous montaditos bar. Arrive early to get a spot.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Quimet+Quimet+Barcelona",
        "travel_time_ub": "20 min en metro (L3)",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["hungry", "adventure"],
    },
    {
        "id": "cal-pep",
        "name": "Cal Pep",
        "name_es": "Cal Pep",
        "lat": 41.3826,
        "lng": 2.1830,
        "address": "Plaça de les Olles, 8, El Born",
        "description_es": "Mariscos y tapas catalanas en el Born. Reserva con antelación.",
        "description_en": "Seafood and Catalan tapas in El Born. Book in advance.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cal+Pep+Barcelona",
        "travel_time_ub": "20 min en metro",
        "time": ["1-2h", "half"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["hungry"],
    },
    {
        "id": "tickets",
        "name": "Tickets Bar",
        "name_es": "Tickets Bar",
        "lat": 41.3742,
        "lng": 2.1502,
        "address": "Av. del Paral·lel, 164, Poble Sec",
        "description_es": "Tapas creativas de los hermanos Adrià. Experiencia culinaria única.",
        "description_en": "Creative tapas by Adrià brothers. Unique culinary experience.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Tickets+Bar+Barcelona",
        "travel_time_ub": "25 min en metro",
        "time": ["half"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["hungry", "adventure"],
    },
    {
        "id": "bar-canete",
        "name": "Bar Cañete",
        "name_es": "Bar Cañete",
        "lat": 41.3795,
        "lng": 2.1730,
        "address": "Carrer de la Unió, 17, El Raval",
        "description_es": "Tapas tradicionales y cocina de mercado cerca de La Rambla.",
        "description_en": "Traditional tapas and market cuisine near La Rambla.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bar+Canete+Barcelona",
        "travel_time_ub": "15 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["hungry"],
    },
    {
        "id": "mercat-sant-antoni",
        "name": "Mercat de Sant Antoni",
        "name_es": "Mercado de Sant Antoni",
        "lat": 41.3789,
        "lng": 2.1670,
        "address": "Carrer del Comte d'Urgell, 1",
        "description_es": "Mercado histórico recién renovado. Puestos de comida y ambiente auténtico.",
        "description_en": "Historic market recently renovated. Food stalls and authentic vibe.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Mercat+Sant+Antoni+Barcelona",
        "travel_time_ub": "12 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry", "cultural"],
    },
    {
        "id": "flax-kale",
        "name": "Flax & Kale",
        "name_es": "Flax & Kale",
        "lat": 41.3856,
        "lng": 2.1706,
        "address": "Carrer dels Tallers, 74b, El Raval",
        "description_es": "Restaurante healthy con opciones veganas y vegetarianas. Bowls y smoothies.",
        "description_en": "Healthy restaurant with vegan and vegetarian options. Bowls and smoothies.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Flax+Kale+Barcelona",
        "travel_time_ub": "10 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry", "chill"],
    },
    {
        "id": "pizzeria-napoletana",
        "name": "NAP Pizzeria Napoletana",
        "name_es": "NAP Pizzeria Napoletana",
        "lat": 41.3919,
        "lng": 2.1651,
        "address": "Carrer de València, 302, Eixample",
        "description_es": "Pizza napolitana auténtica. Masa tradicional y ingredientes italianos.",
        "description_en": "Authentic Neapolitan pizza. Traditional dough and Italian ingredients.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=NAP+Pizzeria+Barcelona",
        "travel_time_ub": "8 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry"],
    },
    {
        "id": "el-xampanyet",
        "name": "El Xampanyet",
        "name_es": "El Xampanyet",
        "lat": 41.3851,
        "lng": 2.1821,
        "address": "Carrer de Montcada, 22, El Born",
        "description_es": "Bar histórico de tapas y cava. Ambiente animado y azulejos clásicos.",
        "description_en": "Historic tapas and cava bar. Lively atmosphere and classic tiles.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=El+Xampanyet+Barcelona",
        "travel_time_ub": "20 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["hungry", "cultural"],
    },
    {
        "id": "cafe-emma",
        "name": "Café Emma",
        "name_es": "Café Emma",
        "lat": 41.3890,
        "lng": 2.1590,
        "address": "Carrer de Pau Claris, 142, Eixample",
        "description_es": "Brunch popular y café de especialidad. Perfecto para empezar el día.",
        "description_en": "Popular brunch spot and specialty coffee. Perfect to start the day.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cafe+Emma+Barcelona",
        "travel_time_ub": "8 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry", "chill"],
    },
    {
        "id": "ciudad-condal",
        "name": "Ciudad Condal",
        "name_es": "Ciudad Condal",
        "lat": 41.3908,
        "lng": 2.1622,
        "address": "Rambla de Catalunya, 18, Eixample",
        "description_es": "Tapas clásicas y raciones generosas. Gran variedad en el mostrador.",
        "description_en": "Classic tapas and generous portions. Great variety at the counter.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Ciudad+Condal+Barcelona",
        "travel_time_ub": "10 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry"],
    },
    {
        "id": "bodega-montferry",
        "name": "Bodega Montferry",
        "name_es": "Bodega Montferry",
        "lat": 41.3900,
        "lng": 2.1570,
        "address": "Carrer de Provença, 171, Eixample",
        "description_es": "Bodega tradicional con vermut de grifo y conservas de calidad.",
        "description_en": "Traditional bodega with vermouth on tap and quality canned goods.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bodega+Montferry+Barcelona",
        "travel_time_ub": "7 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry", "chill"],
    },
    {
        "id": "escriba",
        "name": "Pastisseria Escribà",
        "name_es": "Pastissería Escribà",
        "lat": 41.3788,
        "lng": 2.1743,
        "address": "La Rambla, 83, Ciutat Vella",
        "description_es": "Pastelería modernista famosa. Dulces catalanes y chocolate artesanal.",
        "description_en": "Famous modernist pastry shop. Catalan sweets and artisan chocolate.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Escriba+Barcelona",
        "travel_time_ub": "12 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["hungry", "cultural"],
    },
    {
        "id": "Can-Culleretes",
        "name": "Can Culleretes",
        "name_es": "Can Culleretes",
        "lat": 41.3805,
        "lng": 2.1731,
        "address": "Carrer d'en Quintana, 5, Barri Gòtic",
        "description_es": "Restaurante más antiguo de Barcelona (1786). Cocina catalana tradicional.",
        "description_en": "Barcelona's oldest restaurant (1786). Traditional Catalan cuisine.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Can+Culleretes+Barcelona",
        "travel_time_ub": "15 min a pie",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["hungry", "cultural"],
    },
    {
        "id": "barceloneta-chiringuito",
        "name": "Barceloneta Beach Bars",
        "name_es": "Chiringuitos de la Barceloneta",
        "lat": 41.3784,
        "lng": 2.1925,
        "address": "Passeig Marítim, Barceloneta",
        "description_es": "Bares de playa con paella, pescado frito y cervezas frías.",
        "description_en": "Beach bars with paella, fried fish, and cold beers.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Barceloneta+Beach+Bars",
        "travel_time_ub": "20 min en metro (L4)",
        "time": ["1-2h", "half"],
        "location": ["beach", "barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["hungry", "chill"],
    },
    
    # CULTURAL - Museums, Galleries, Historic Sites, Architecture (17 places)
    {
        "id": "sagrada-familia",
        "name": "Sagrada Família",
        "name_es": "La Sagrada Família",
        "lat": 41.4036,
        "lng": 2.1744,
        "address": "Carrer de Mallorca, 401",
        "description_es": "Basílica de Gaudí, símbolo de Barcelona. Compra entradas online para evitar colas.",
        "description_en": "Gaudí's basilica, symbol of Barcelona. Buy tickets online to skip lines.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sagrada+Familia",
        "travel_time_ub": "12 min en metro (L2/L5)",
        "time": ["half", "full"],
        "location": ["ub", "barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["cultural", "adventure"],
    },
    {
        "id": "park-guell",
        "name": "Park Güell",
        "name_es": "Parque Güell",
        "lat": 41.4145,
        "lng": 2.1527,
        "address": "Carrer d'Olot, Gràcia",
        "description_es": "Parque modernista de Gaudí con vistas de la ciudad. Reserva entrada con antelación.",
        "description_en": "Gaudí's modernist park with city views. Book tickets in advance.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Park+Guell+Barcelona",
        "travel_time_ub": "25 min en metro (L3)",
        "time": ["half", "full"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["adventure", "cultural"],
    },
    {
        "id": "mnac",
        "name": "MNAC",
        "name_es": "Museo Nacional de Arte de Cataluña",
        "lat": 41.3681,
        "lng": 2.1537,
        "address": "Parc de Montjuïc",
        "description_es": "Arte catalán y vistas desde la montaña de Montjuïc. Buen plan cultural de medio día.",
        "description_en": "Catalan art and views from Montjuïc hill. A solid half-day cultural plan.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=MNAC+Barcelona",
        "travel_time_ub": "18 min en metro + funicular",
        "time": ["half", "full"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["cultural", "chill"],
    },
    {
        "id": "el-born",
        "name": "El Born cultural center",
        "name_es": "El Born CCultural",
        "lat": 41.3843,
        "lng": 2.1837,
        "address": "Plaça Comercial, 12",
        "description_es": "Ruinas arqueológicas y exposiciones sobre la historia de Barcelona.",
        "description_en": "Archaeological ruins and exhibits on Barcelona's history.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=El+Born+Centre+Cultural",
        "travel_time_ub": "18 min en metro",
        "time": ["1-2h", "half"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["cultural"],
    },
    {
        "id": "picasso-museum",
        "name": "Picasso Museum",
        "name_es": "Museo Picasso",
        "lat": 41.3851,
        "lng": 2.1805,
        "address": "Carrer de Montcada, 15-23, El Born",
        "description_es": "Colección extensa de obras tempranas de Picasso. Reserva online.",
        "description_en": "Extensive collection of Picasso's early works. Book online.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Picasso+Museum+Barcelona",
        "travel_time_ub": "20 min en metro",
        "time": ["1-2h", "half"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["cultural"],
    },
    {
        "id": "casa-batllo",
        "name": "Casa Batlló",
        "name_es": "Casa Batlló",
        "lat": 41.3916,
        "lng": 2.1649,
        "address": "Passeig de Gràcia, 43, Eixample",
        "description_es": "Obra maestra de Gaudí con fachada ondulante. Audio guía interactiva incluida.",
        "description_en": "Gaudí masterpiece with undulating facade. Interactive audio guide included.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Casa+Batllo+Barcelona",
        "travel_time_ub": "8 min a pie",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["cultural"],
    },
    {
        "id": "casa-mila",
        "name": "Casa Milà (La Pedrera)",
        "name_es": "Casa Milà (La Pedrera)",
        "lat": 41.3954,
        "lng": 2.1620,
        "address": "Passeig de Gràcia, 92, Eixample",
        "description_es": "Otra obra de Gaudí con azotea única. Vistas panorámicas de la ciudad.",
        "description_en": "Another Gaudí work with unique rooftop. Panoramic city views.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=La+Pedrera+Barcelona",
        "travel_time_ub": "10 min a pie",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["cultural"],
    },
    {
        "id": "gothic-quarter",
        "name": "Gothic Quarter",
        "name_es": "Barrio Gótico",
        "lat": 41.3828,
        "lng": 2.1769,
        "address": "Barri Gòtic, Ciutat Vella",
        "description_es": "Calles medievales, catedral y plazas escondidas. Perfecto para pasear.",
        "description_en": "Medieval streets, cathedral, and hidden squares. Perfect for wandering.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Gothic+Quarter+Barcelona",
        "travel_time_ub": "15 min a pie",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["cultural", "adventure"],
    },
    {
        "id": "palau-musica",
        "name": "Palau de la Música",
        "name_es": "Palau de la Música Catalana",
        "lat": 41.3875,
        "lng": 2.1753,
        "address": "Carrer del Palau de la Música, 4-6",
        "description_es": "Sala de conciertos modernista con vitrales espectaculares. Tours guiados disponibles.",
        "description_en": "Modernist concert hall with spectacular stained glass. Guided tours available.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Palau+Musica+Barcelona",
        "travel_time_ub": "12 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["cultural"],
    },
    {
        "id": "miro-foundation",
        "name": "Fundació Joan Miró",
        "name_es": "Fundación Joan Miró",
        "lat": 41.3687,
        "lng": 2.1599,
        "address": "Parc de Montjuïc",
        "description_es": "Museo dedicado a Miró con vistas de Montjuïc. Arte moderno catalán.",
        "description_en": "Museum dedicated to Miró with Montjuïc views. Catalan modern art.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Fundacio+Miro+Barcelona",
        "travel_time_ub": "22 min en metro + funicular",
        "time": ["half"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["cultural", "chill"],
    },
    {
        "id": "barcelona-cathedral",
        "name": "Barcelona Cathedral",
        "name_es": "Catedral de Barcelona",
        "lat": 41.3841,
        "lng": 2.1760,
        "address": "Pla de la Seu, Barri Gòtic",
        "description_es": "Catedral gótica del siglo XIII con claustro y gansos. Entrada gratuita en horarios específicos.",
        "description_en": "13th-century Gothic cathedral with cloister and geese. Free entry at specific times.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Barcelona+Cathedral",
        "travel_time_ub": "15 min a pie",
        "time": ["1-2h"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["cultural"],
    },
    {
        "id": "santa-maria-del-mar",
        "name": "Santa Maria del Mar",
        "name_es": "Santa Maria del Mar",
        "lat": 41.3836,
        "lng": 2.1825,
        "address": "Plaça de Santa Maria, 1, El Born",
        "description_es": "Basílica gótica elegante en el Born. Acústica impresionante para conciertos.",
        "description_en": "Elegant Gothic basilica in El Born. Impressive acoustics for concerts.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Santa+Maria+del+Mar+Barcelona",
        "travel_time_ub": "20 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["cultural", "chill"],
    },
    {
        "id": "macba",
        "name": "MACBA",
        "name_es": "Museo de Arte Contemporáneo de Barcelona",
        "lat": 41.3830,
        "lng": 2.1668,
        "address": "Plaça dels Àngels, 1, El Raval",
        "description_es": "Arte contemporáneo en edificio moderno. Plaza popular con skaters.",
        "description_en": "Contemporary art in modern building. Popular plaza with skateboarders.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=MACBA+Barcelona",
        "travel_time_ub": "12 min a pie",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk"],
        "mood": ["cultural", "adventure"],
    },
    {
        "id": "hospital-sant-pau",
        "name": "Hospital de Sant Pau",
        "name_es": "Recinto Modernista de Sant Pau",
        "lat": 41.4144,
        "lng": 2.1746,
        "address": "Carrer de Sant Quintí, 89",
        "description_es": "Hospital modernista diseñado por Domènech i Montaner. Pabellones y jardines.",
        "description_en": "Modernist hospital designed by Domènech i Montaner. Pavilions and gardens.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Hospital+Sant+Pau+Barcelona",
        "travel_time_ub": "15 min en metro (L5)",
        "time": ["1-2h", "half"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["cultural"],
    },
    {
        "id": "camp-nou-tour",
        "name": "Spotify Camp Nou tour",
        "name_es": "Tour del Camp Nou (FC Barcelona)",
        "lat": 41.3809,
        "lng": 2.1228,
        "address": "C. d'Aristides Maillol, Les Corts",
        "description_es": "Museo y estadio del Barça; imprescindible si te gusta el fútbol español.",
        "description_en": "Barça museum and stadium; essential if you love Spanish football.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Camp+Nou",
        "travel_time_ub": "20 min en metro (L3)",
        "time": ["half"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["cultural", "adventure"],
    },
    {
        "id": "poble-espanyol",
        "name": "Poble Espanyol",
        "name_es": "Poble Espanyol",
        "lat": 41.3683,
        "lng": 2.1487,
        "address": "Av. Francesc Ferrer i Guàrdia, 13, Montjuïc",
        "description_es": "Museo al aire libre con arquitectura española de todas las regiones.",
        "description_en": "Open-air museum with Spanish architecture from all regions.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Poble+Espanyol+Barcelona",
        "travel_time_ub": "25 min en metro",
        "time": ["half", "full"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["cultural", "adventure"],
    },
    {
        "id": "magic-fountain",
        "name": "Magic Fountain of Montjuïc",
        "name_es": "Fuente Mágica de Montjuïc",
        "lat": 41.3719,
        "lng": 2.1519,
        "address": "Plaça de Carles Buïgas, Montjuïc",
        "description_es": "Espectáculo de luces, agua y música. Gratis por la noche (verifica horarios).",
        "description_en": "Light, water, and music show. Free at night (check schedule).",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Magic+Fountain+Montjuic",
        "travel_time_ub": "20 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["cultural", "adventure"],
    },
    
    # CHILL - Parks, Beaches, Gardens, Quiet Neighborhoods (13 places)
    {
        "id": "barceloneta",
        "name": "Barceloneta Beach",
        "name_es": "Playa de la Barceloneta",
        "lat": 41.3784,
        "lng": 2.1925,
        "address": "Passeig Marítim, Barceloneta",
        "description_es": "Playa urbana para relajarse, pasear y comer en chiringuitos.",
        "description_en": "Urban beach to relax, stroll, and eat at beach bars.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Barceloneta+Beach",
        "travel_time_ub": "20 min en metro (L4)",
        "time": ["1-2h", "half", "full"],
        "location": ["beach", "barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["chill", "hungry"],
    },
    {
        "id": "ciutadella",
        "name": "Parc de la Ciutadella",
        "name_es": "Parque de la Ciutadella",
        "lat": 41.3881,
        "lng": 2.1860,
        "address": "Passeig de Picasso, 21",
        "description_es": "Parque grande cerca del Born: paseo, picnic y el Arc de Triomf.",
        "description_en": "Large park near El Born: walks, picnic, and Arc de Triomf.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+de+la+Ciutadella",
        "travel_time_ub": "15 min en metro o bici",
        "time": ["1-2h", "half"],
        "location": ["ub", "barcelona"],
        "distance": ["walk", "transit"],
        "mood": ["chill", "cultural"],
    },
    {
        "id": "bunkers-carmel",
        "name": "Bunkers del Carmel",
        "name_es": "Búnkeres del Carmel",
        "lat": 41.4171,
        "lng": 2.1576,
        "address": "Carrer de Marià Labèrnia, El Carmel",
        "description_es": "Mirador panorámico 360° de Barcelona. Ideal para atardecer.",
        "description_en": "360° panoramic viewpoint of Barcelona. Perfect for sunset.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bunkers+del+Carmel",
        "travel_time_ub": "30 min en metro + subida",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["chill", "adventure"],
    },
    {
        "id": "mar-bella",
        "name": "Mar Bella Beach",
        "name_es": "Playa de la Mar Bella",
        "lat": 41.4024,
        "lng": 2.2108,
        "address": "Passeig Marítim del Bogatell",
        "description_es": "Playa más tranquila con zona nudista. Ambiente relajado.",
        "description_en": "Quieter beach with nudist area. Relaxed atmosphere.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Mar+Bella+Beach+Barcelona",
        "travel_time_ub": "30 min en metro (L4)",
        "time": ["half", "full"],
        "location": ["beach", "barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["chill"],
    },
    {
        "id": "jardins-laribal",
        "name": "Jardins de Laribal",
        "name_es": "Jardines de Laribal",
        "lat": 41.3697,
        "lng": 2.1590,
        "address": "Montjuïc",
        "description_es": "Jardines escalonados con fuentes y vistas. Paseo tranquilo en Montjuïc.",
        "description_en": "Terraced gardens with fountains and views. Peaceful walk in Montjuïc.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Jardins+Laribal+Barcelona",
        "travel_time_ub": "22 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["chill", "cultural"],
    },
    {
        "id": "tibidabo",
        "name": "Tibidabo",
        "name_es": "Tibidabo",
        "lat": 41.4231,
        "lng": 2.1188,
        "address": "Plaça del Tibidabo, 3-4",
        "description_es": "Montaña con parque de atracciones vintage y vistas panorámicas.",
        "description_en": "Mountain with vintage amusement park and panoramic views.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Tibidabo+Barcelona",
        "travel_time_ub": "40 min en metro + funicular",
        "time": ["half", "full"],
        "location": ["barcelona"],
        "distance": ["anywhere"],
        "mood": ["chill", "adventure"],
    },
    {
        "id": "labyrinth-park",
        "name": "Parc del Laberint d'Horta",
        "name_es": "Parque del Laberinto de Horta",
        "lat": 41.4384,
        "lng": 2.1469,
        "address": "Passeig dels Castanyers, 1",
        "description_es": "Jardín neoclásico con laberinto de cipreses. Parque histórico y tranquilo.",
        "description_en": "Neoclassical garden with cypress labyrinth. Historic and quiet park.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+Laberint+Horta",
        "travel_time_ub": "35 min en metro (L3)",
        "time": ["1-2h", "half"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["chill", "cultural"],
    },
    {
        "id": "montjuic-castle",
        "name": "Montjuïc Castle",
        "name_es": "Castillo de Montjuïc",
        "lat": 41.3648,
        "lng": 2.1664,
        "address": "Carretera de Montjuïc, 66",
        "description_es": "Fortaleza histórica con vistas del puerto. Teleférico disponible.",
        "description_en": "Historic fortress with port views. Cable car available.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Montjuic+Castle+Barcelona",
        "travel_time_ub": "25 min en metro + teleférico",
        "time": ["half"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["chill", "cultural"],
    },
    {
        "id": "jardins-mossen-cinto",
        "name": "Jardins de Mossèn Cinto Verdaguer",
        "name_es": "Jardines de Mossèn Cinto Verdaguer",
        "lat": 41.3664,
        "lng": 2.1634,
        "address": "Montjuïc",
        "description_es": "Jardín botánico con flores acuáticas y bulbos. Perfecto para pasear.",
        "description_en": "Botanical garden with aquatic flowers and bulbs. Perfect for strolling.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Jardins+Mossen+Cinto+Barcelona",
        "travel_time_ub": "25 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["chill"],
    },
    {
        "id": "bogatell-beach",
        "name": "Bogatell Beach",
        "name_es": "Playa del Bogatell",
        "lat": 41.3952,
        "lng": 2.2059,
        "address": "Passeig Marítim del Bogatell",
        "description_es": "Playa amplia y menos concurrida que Barceloneta. Ideal para volley playa.",
        "description_en": "Wide beach less crowded than Barceloneta. Great for beach volleyball.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bogatell+Beach+Barcelona",
        "travel_time_ub": "25 min en metro (L4)",
        "time": ["half", "full"],
        "location": ["beach", "barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["chill"],
    },
    {
        "id": "parc-cervantes",
        "name": "Parc de Cervantes",
        "name_es": "Parque de Cervantes",
        "lat": 41.3868,
        "lng": 2.1129,
        "address": "Av. Diagonal, 708",
        "description_es": "Parque de rosas con más de 11,000 rosales. Colorido en primavera.",
        "description_en": "Rose park with over 11,000 rose bushes. Colorful in spring.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+Cervantes+Barcelona",
        "travel_time_ub": "25 min en metro (L3)",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["chill"],
    },
    {
        "id": "passeig-born",
        "name": "Passeig del Born",
        "name_es": "Paseo del Born",
        "lat": 41.3847,
        "lng": 2.1831,
        "address": "Passeig del Born, El Born",
        "description_es": "Bulevar animado con terrazas y tiendas. Buen lugar para un paseo.",
        "description_en": "Lively boulevard with terraces and shops. Great for a stroll.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Passeig+del+Born+Barcelona",
        "travel_time_ub": "20 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["chill", "cultural"],
    },
    {
        "id": "jardins-miramar",
        "name": "Jardins de Miramar",
        "name_es": "Jardines de Miramar",
        "lat": 41.3689,
        "lng": 2.1653,
        "address": "Montjuïc",
        "description_es": "Mirador con vistas al puerto y la ciudad. Zona tranquila en Montjuïc.",
        "description_en": "Viewpoint with port and city views. Quiet area in Montjuïc.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Jardins+Miramar+Barcelona",
        "travel_time_ub": "22 min en metro",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["chill"],
    },
    
    # ADVENTURE - Day Trips, Outdoor Activities, Unique Experiences (9 places)
    {
        "id": "montserrat",
        "name": "Montserrat",
        "name_es": "Montserrat",
        "lat": 41.5933,
        "lng": 1.8375,
        "address": "Monistrol de Montserrat, Catalonia",
        "description_es": "Monasterio en la montaña; excursion de día en tren desde Barcelona.",
        "description_en": "Mountain monastery; day trip by train from Barcelona.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Montserrat+Monastery",
        "travel_time_ub": "~1 h 30 en tren + cremallera",
        "time": ["full"],
        "location": ["spain"],
        "distance": ["anywhere"],
        "mood": ["adventure", "cultural"],
    },
    {
        "id": "sitges",
        "name": "Sitges",
        "name_es": "Sitges",
        "lat": 41.2370,
        "lng": 1.8055,
        "address": "Sitges, Barcelona province",
        "description_es": "Pueblo costero con playas y calles peatonales; tren Rodalies desde Sants.",
        "description_en": "Coastal town with beaches and pedestrian streets; Rodalies train from Sants.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sitges",
        "travel_time_ub": "~40 min en tren desde Sants",
        "time": ["half", "full"],
        "location": ["spain", "beach"],
        "distance": ["anywhere"],
        "mood": ["chill", "adventure"],
    },
    {
        "id": "collserola",
        "name": "Collserola Natural Park",
        "name_es": "Parque Natural de Collserola",
        "lat": 41.4208,
        "lng": 2.1128,
        "address": "Collserola, Barcelona",
        "description_es": "Parque natural para senderismo y ciclismo. Rutas con vistas de Barcelona.",
        "description_en": "Natural park for hiking and cycling. Trails with Barcelona views.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Collserola+Park+Barcelona",
        "travel_time_ub": "35 min en metro + bus",
        "time": ["half", "full"],
        "location": ["barcelona"],
        "distance": ["anywhere"],
        "mood": ["adventure", "chill"],
    },
    {
        "id": "costa-brava",
        "name": "Costa Brava Beaches",
        "name_es": "Playas de la Costa Brava",
        "lat": 41.6523,
        "lng": 2.8259,
        "address": "Costa Brava, Girona",
        "description_es": "Calas rocosas y pueblos costeros. Tossa de Mar, Calella de Palafrugell.",
        "description_en": "Rocky coves and coastal villages. Tossa de Mar, Calella de Palafrugell.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Costa+Brava+Spain",
        "travel_time_ub": "~1 h 30 en coche o bus",
        "time": ["full"],
        "location": ["spain", "beach"],
        "distance": ["anywhere"],
        "mood": ["adventure", "chill"],
    },
    {
        "id": "port-aventura",
        "name": "PortAventura World",
        "name_es": "PortAventura World",
        "lat": 41.0858,
        "lng": 1.1552,
        "address": "Tarragona",
        "description_es": "Parque temático con montañas rusas y espectáculos. Tren directo desde Barcelona.",
        "description_en": "Theme park with roller coasters and shows. Direct train from Barcelona.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=PortAventura",
        "travel_time_ub": "~1 h 15 en tren",
        "time": ["full"],
        "location": ["spain"],
        "distance": ["anywhere"],
        "mood": ["adventure"],
    },
    {
        "id": "kayaking-barcelona",
        "name": "Barcelona Beach Kayaking",
        "name_es": "Kayak en la playa de Barcelona",
        "lat": 41.3831,
        "lng": 2.1969,
        "address": "Port Olímpic, Barcelona",
        "description_es": "Alquiler de kayak en el Puerto Olímpico. Ruta por la costa.",
        "description_en": "Kayak rental at Olympic Port. Coastal route.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Kayak+Port+Olympic+Barcelona",
        "travel_time_ub": "25 min en metro (L4)",
        "time": ["1-2h", "half"],
        "location": ["beach", "barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["adventure"],
    },
    {
        "id": "bike-tour",
        "name": "Barcelona Bike Tour",
        "name_es": "Tour en bici por Barcelona",
        "lat": 41.3851,
        "lng": 2.1734,
        "address": "Centro de Barcelona",
        "description_es": "Recorre la ciudad en bici: playa, Gaudí, Gótico. Varias empresas ofrecen tours.",
        "description_en": "Explore the city by bike: beach, Gaudí, Gothic. Various companies offer tours.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Barcelona+Bike+Tours",
        "travel_time_ub": "Salida desde varios puntos",
        "time": ["half"],
        "location": ["barcelona"],
        "distance": ["transit", "anywhere"],
        "mood": ["adventure", "cultural"],
    },
    {
        "id": "cable-car",
        "name": "Montjuïc Cable Car",
        "name_es": "Teleférico de Montjuïc",
        "lat": 41.3713,
        "lng": 2.1673,
        "address": "Montjuïc",
        "description_es": "Teleférico desde el puerto hasta el castillo. Vistas aéreas de Barcelona.",
        "description_en": "Cable car from port to castle. Aerial views of Barcelona.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Teleferic+Montjuic",
        "travel_time_ub": "25 min en metro al inicio",
        "time": ["1-2h"],
        "location": ["barcelona"],
        "distance": ["transit"],
        "mood": ["adventure", "cultural"],
    },
    {
        "id": "girona-day-trip",
        "name": "Girona Day Trip",
        "name_es": "Excursión a Girona",
        "lat": 41.9794,
        "lng": 2.8214,
        "address": "Girona, Catalonia",
        "description_es": "Ciudad medieval con murallas, catedral y barrio judío. Tren rápido desde Barcelona.",
        "description_en": "Medieval city with walls, cathedral, and Jewish quarter. Fast train from Barcelona.",
        "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Girona+Spain",
        "travel_time_ub": "~40 min en tren AVE",
        "time": ["full"],
        "location": ["spain"],
        "distance": ["anywhere"],
        "mood": ["adventure", "cultural"],
    },
]


def _mood_to_place_types(mood: str | None) -> list[str]:
    """Map mood filter to Google Places API types."""
    mood_map = {
        "hungry": ["restaurant", "cafe", "bar"],
        "cultural": ["museum", "art_gallery", "tourist_attraction", "church"],
        "chill": ["park", "natural_feature"],
        "adventure": ["tourist_attraction", "amusement_park", "stadium"],
    }
    return mood_map.get(mood or "", [])


def _location_to_coordinates(location: str | None) -> tuple[float, float]:
    """Map location filter to lat/lng coordinates for search center."""
    location_map = {
        "ub": (UB_LAT, UB_LNG),
        "barcelona": (41.3874, 2.1686),
        "beach": (41.3784, 2.1925),
        "spain": (41.3874, 2.1686),
    }
    return location_map.get(location or "barcelona", (UB_LAT, UB_LNG))


def fetch_google_places(
    mood: str | None = None,
    location: str | None = None,
    max_results: int = 10,
) -> list[dict[str, Any]]:
    """
    Query Google Places API (New) for dynamic recommendations.
    Returns empty list if API key is missing or request fails.
    
    Requires GOOGLE_PLACES_API_KEY environment variable.
    """
    api_key = os.getenv("GOOGLE_PLACES_API_KEY", "").strip()
    if not api_key:
        logger.debug("Google Places API key not configured, skipping API call")
        return []
    
    place_types = _mood_to_place_types(mood)
    if not place_types:
        logger.debug("No place types for mood=%s, skipping API call", mood)
        return []
    
    center_lat, center_lng = _location_to_coordinates(location)
    
    radius = 5000 if location == "ub" else 15000
    
    try:
        results = []
        for place_type in place_types[:2]:
            url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
            params = {
                "location": f"{center_lat},{center_lng}",
                "radius": radius,
                "type": place_type,
                "key": api_key,
            }
            
            response = requests.get(url, params=params, timeout=5)
            response.raise_for_status()
            data = response.json()
            
            if data.get("status") != "OK":
                logger.warning("Google Places API returned status: %s", data.get("status"))
                continue
            
            for place in data.get("results", [])[:5]:
                place_id = place.get("place_id")
                name = place.get("name", "")
                loc = place.get("geometry", {}).get("location", {})
                lat = loc.get("lat")
                lng = loc.get("lng")
                address = place.get("vicinity", "")
                
                if not all([place_id, name, lat, lng]):
                    continue
                
                results.append({
                    "id": f"google-{place_id}",
                    "name": name,
                    "name_es": name,
                    "lat": lat,
                    "lng": lng,
                    "address": address,
                    "description_es": f"Recomendación de Google Maps cerca de {location or 'Barcelona'}.",
                    "description_en": f"Google Maps recommendation near {location or 'Barcelona'}.",
                    "google_maps_url": f"https://www.google.com/maps/search/?api=1&query={name.replace(' ', '+')}+Barcelona&query_place_id={place_id}",
                    "travel_time_ub": "Ver en Google Maps",
                    "time": [],
                    "location": [location or "barcelona"],
                    "distance": [],
                    "mood": [mood] if mood else [],
                    "_source": "google_api",
                })
                
                if len(results) >= max_results:
                    break
            
            if len(results) >= max_results:
                break
        
        logger.info("Fetched %d places from Google Places API", len(results))
        return results[:max_results]
    
    except requests.RequestException as exc:
        logger.warning("Google Places API request failed: %s", exc)
        return []
    except Exception as exc:
        logger.error("Unexpected error in fetch_google_places: %s", exc)
        return []


def filter_travel_recommendations(
    time: str | None = None,
    location: str | None = None,
    distance: str | None = None,
    mood: str | None = None,
) -> list[dict[str, Any]]:
    """Return up to 5 recommendations matching filter tags."""
    scored: list[tuple[int, dict[str, Any]]] = []
    for rec in TRAVEL_RECOMMENDATIONS_SEED:
        score = 0
        if time and time in rec.get("time", []):
            score += 2
        elif not time:
            score += 1
        if location and location in rec.get("location", []):
            score += 2
        elif not location:
            score += 1
        if distance and distance in rec.get("distance", []):
            score += 2
        elif not distance:
            score += 1
        if mood and mood in rec.get("mood", []):
            score += 2
        elif not mood:
            score += 1
        if time and time not in rec.get("time", []):
            continue
        if location and location not in rec.get("location", []):
            continue
        if distance and distance not in rec.get("distance", []):
            continue
        if mood and mood not in rec.get("mood", []):
            continue
        scored.append((score, dict(rec)))

    scored.sort(key=lambda x: x[0], reverse=True)
    results = [r for _, r in scored[:5]]
    return results
