"""Seed data for Estudio Abroad — imported by fetcher.py."""

FLASHCARD_DECK_SEED = [
    {"es": 'la estación de metro', "en": 'the metro station'},
    {"es": 'el andén', "en": 'the platform'},
    {"es": '¿A qué hora sale el próximo metro?', "en": 'What time does the next metro leave?'},
    {"es": 'un billete sencillo', "en": 'a single ticket'},
    {"es": 'un abono de transporte', "en": 'a transport pass'},
    {"es": 'la línea de metro', "en": 'the metro line'},
    {"es": 'el mapa del metro', "en": 'the metro map'},
    {"es": 'la parada de autobús', "en": 'the bus stop'},
    {"es": 'el billete de bus', "en": 'the bus ticket'},
    {"es": 'la tarjeta T-usual', "en": 'the T-usual card'},
    {"es": 'validar el billete', "en": 'to validate the ticket'},
    {"es": 'el transbordo', "en": 'the transfer'},
    {"es": 'la estación de Rodalies', "en": 'the Rodalies station'},
    {"es": 'el tren de cercanías', "en": 'the commuter train'},
    {"es": '¿Dónde está la salida?', "en": 'Where is the exit?'},
    {"es": 'el ascensor', "en": 'the elevator'},
    {"es": 'las escaleras mecánicas', "en": 'the escalators'},
    {"es": 'el retraso del tren', "en": 'the train delay'},
    {"es": 'la huelga de transporte', "en": 'the transport strike'},
    {"es": 'el aeropuerto de El Prat', "en": 'El Prat airport'},
    {"es": 'el aerobús', "en": 'the airport bus'},
    {"es": 'un taxi oficial', "en": 'an official taxi'},
    {"es": 'la parada de taxi', "en": 'the taxi rank'},
    {"es": 'el atasco de tráfico', "en": 'the traffic jam'},
    {"es": 'la zona azul', "en": 'the blue parking zone'},
    {"es": 'el menú del día', "en": 'the set lunch menu'},
    {"es": 'la cuenta, por favor', "en": 'the bill, please'},
    {"es": '¿Cuánto cuesta?', "en": 'How much does it cost?'},
    {"es": 'una mesa para dos', "en": 'a table for two'},
    {"es": 'sin gluten', "en": 'gluten-free'},
    {"es": 'alergia a los frutos secos', "en": 'nut allergy'},
    {"es": 'la propina', "en": 'the tip'},
    {"es": 'el camarero', "en": 'the waiter'},
    {"es": 'la carta de vinos', "en": 'the wine list'},
    {"es": 'un café con leche', "en": 'a coffee with milk'},
    {"es": 'una cerveza pequeña', "en": 'a small beer'},
    {"es": 'agua sin gas', "en": 'still water'},
    {"es": 'agua con gas', "en": 'sparkling water'},
    {"es": 'para llevar', "en": 'to take away'},
    {"es": 'la terraza', "en": 'the terrace'},
    {"es": 'el desayuno', "en": 'breakfast'},
    {"es": 'la comida', "en": 'lunch'},
    {"es": 'la cena', "en": 'dinner'},
    {"es": 'el postre', "en": 'dessert'},
    {"es": 'está delicioso', "en": "it's delicious"},
    {"es": 'sin cebolla', "en": 'without onion'},
    {"es": 'bien hecho', "en": 'well done'},
    {"es": 'poco hecho', "en": 'rare'},
    {"es": 'la reserva', "en": 'the reservation'},
    {"es": '¿Tienen menú en inglés?', "en": 'Do you have a menu in English?'},
    {"es": 'el mercado municipal', "en": 'the municipal market'},
    {"es": 'La Boqueria', "en": 'La Boqueria market'},
    {"es": 'un kilo de tomates', "en": 'a kilo of tomatoes'},
    {"es": 'medio kilo', "en": 'half a kilo'},
    {"es": '¿Cuánto pesa?', "en": 'How much does it weigh?'},
    {"es": 'la bolsa reutilizable', "en": 'the reusable bag'},
    {"es": 'el pescadero', "en": 'the fishmonger'},
    {"es": 'la frutería', "en": 'the greengrocer'},
    {"es": 'fresco del día', "en": 'fresh today'},
    {"es": 'la oferta', "en": 'the special offer'},
    {"es": 'el precio por kilo', "en": 'the price per kilo'},
    {"es": '¿Puedo probarlo?', "en": 'Can I try it?'},
    {"es": 'la cola en la caja', "en": 'the queue at the checkout'},
    {"es": 'pagar en efectivo', "en": 'to pay in cash'},
    {"es": 'pagar con tarjeta', "en": 'to pay by card'},
    {"es": 'el centro de salud', "en": 'the health center'},
    {"es": 'la tarjeta sanitaria', "en": 'the health card'},
    {"es": 'pedir cita médica', "en": "to request a doctor's appointment"},
    {"es": 'la farmacia', "en": 'the pharmacy'},
    {"es": 'la receta médica', "en": 'the prescription'},
    {"es": '¿Dónde está la urgencia?', "en": 'Where is the emergency room?'},
    {"es": 'me duele la cabeza', "en": 'my head hurts'},
    {"es": 'tengo fiebre', "en": 'I have a fever'},
    {"es": 'la alergia', "en": 'the allergy'},
    {"es": 'el seguro médico', "en": 'health insurance'},
    {"es": 'la mutua', "en": 'the private health insurer'},
    {"es": 'el médico de cabecera', "en": 'the GP'},
    {"es": 'la enfermera', "en": 'the nurse'},
    {"es": 'las pastillas', "en": 'the pills'},
    {"es": 'la baja médica', "en": 'sick leave'},
    {"es": 'el piso compartido', "en": 'the shared flat'},
    {"es": 'el contrato de alquiler', "en": 'the rental contract'},
    {"es": 'la fianza', "en": 'the deposit'},
    {"es": 'el casero', "en": 'the landlord'},
    {"es": 'la comunidad de vecinos', "en": "the residents' association"},
    {"es": 'las facturas', "en": 'the bills'},
    {"es": 'el recibo del alquiler', "en": 'the rent receipt'},
    {"es": 'la avería', "en": 'the breakdown / fault'},
    {"es": 'el fontanero', "en": 'the plumber'},
    {"es": 'la calefacción', "en": 'the heating'},
    {"es": 'el aire acondicionado', "en": 'the air conditioning'},
    {"es": 'las obras en el edificio', "en": 'building works'},
    {"es": 'el piso amueblado', "en": 'the furnished flat'},
    {"es": 'buscar piso', "en": 'to look for a flat'},
    {"es": 'la agencia inmobiliaria', "en": 'the estate agency'},
    {"es": 'la universidad', "en": 'the university'},
    {"es": 'la matrícula', "en": 'enrollment'},
    {"es": 'el horario de clases', "en": 'the class schedule'},
    {"es": 'el campus', "en": 'the campus'},
    {"es": 'la biblioteca', "en": 'the library'},
    {"es": 'el profesor', "en": 'the professor'},
    {"es": 'la asignatura', "en": 'the subject / course'},
    {"es": 'el examen final', "en": 'the final exam'},
    {"es": 'la nota', "en": 'the grade'},
    {"es": 'el trabajo en grupo', "en": 'group work'},
    {"es": 'la beca', "en": 'the scholarship'},
    {"es": 'el intercambio', "en": 'the exchange program'},
    {"es": 'la secretaría académica', "en": 'the academic office'},
    {"es": 'el carnet de estudiante', "en": 'the student ID'},
    {"es": 'la tutoría', "en": 'the tutorial session'},
    {"es": '¿Dónde está el baño?', "en": 'Where is the bathroom?'},
    {"es": 'a la derecha', "en": 'to the right'},
    {"es": 'a la izquierda', "en": 'to the left'},
    {"es": 'todo recto', "en": 'straight ahead'},
    {"es": 'la esquina', "en": 'the corner'},
    {"es": 'la plaza', "en": 'the square'},
    {"es": 'el semáforo', "en": 'the traffic light'},
    {"es": 'el paso de peatones', "en": 'the crosswalk'},
    {"es": '¿Está lejos?', "en": 'Is it far?'},
    {"es": '¿Está cerca?', "en": 'Is it near?'},
    {"es": 'a cinco minutos a pie', "en": 'five minutes on foot'},
    {"es": 'el mapa', "en": 'the map'},
    {"es": 'perderse', "en": 'to get lost'},
    {"es": '¿Cómo llego a...?', "en": 'How do I get to...?'},
    {"es": 'la dirección', "en": 'the address / direction'},
    {"es": 'buenos días', "en": 'good morning'},
    {"es": 'buenas tardes', "en": 'good afternoon'},
    {"es": 'buenas noches', "en": 'good evening'},
    {"es": 'muchas gracias', "en": 'thank you very much'},
    {"es": 'de nada', "en": "you're welcome"},
    {"es": 'perdón', "en": 'sorry / excuse me'},
    {"es": 'encantado de conocerte', "en": 'nice to meet you'},
    {"es": '¿Qué tal?', "en": "How's it going?"},
    {"es": 'hasta luego', "en": 'see you later'},
    {"es": 'nos vemos', "en": 'see you'},
    {"es": '¿De dónde eres?', "en": 'Where are you from?'},
    {"es": 'soy estudiante', "en": "I'm a student"},
    {"es": 'hablo un poco de español', "en": 'I speak a little Spanish'},
    {"es": '¿Puedes repetir?', "en": 'Can you repeat that?'},
    {"es": 'más despacio, por favor', "en": 'more slowly, please'},
    {"es": 'hace sol', "en": "it's sunny"},
    {"es": 'está lloviendo', "en": "it's raining"},
    {"es": 'hace frío', "en": "it's cold"},
    {"es": 'hace calor', "en": "it's hot"},
    {"es": 'el pronóstico del tiempo', "en": 'the weather forecast'},
    {"es": 'la tormenta', "en": 'the storm'},
    {"es": 'el viento', "en": 'the wind'},
    {"es": 'la humedad', "en": 'the humidity'},
    {"es": '¿Qué tiempo hace?', "en": "What's the weather like?"},
    {"es": 'la ola de calor', "en": 'the heat wave'},
    {"es": 'el empadronamiento', "en": 'municipal registration'},
    {"es": 'el NIE', "en": 'foreigner ID number'},
    {"es": 'la residencia', "en": 'residence permit'},
    {"es": 'la cita previa', "en": 'the prior appointment'},
    {"es": 'la oficina de extranjería', "en": 'the immigration office'},
    {"es": 'el certificado', "en": 'the certificate'},
    {"es": 'la documentación', "en": 'the paperwork'},
    {"es": 'el formulario', "en": 'the form'},
    {"es": 'firmar el contrato', "en": 'to sign the contract'},
    {"es": 'la copia compulsada', "en": 'the certified copy'},
    {"es": 'tramitar el visado', "en": 'to process the visa'},
    {"es": 'la cola en la oficina', "en": 'the queue at the office'},
    {"es": 'el número de turno', "en": 'the queue number'},
    {"es": 'la tasa administrativa', "en": 'the administrative fee'},
    {"es": 'presentar la solicitud', "en": 'to submit the application'},
    {"es": 'sortida', "en": 'exit (Catalan)'},
    {"es": 'entrada', "en": 'entrance (Catalan)'},
    {"es": 'obert', "en": 'open (Catalan)'},
    {"es": 'tancat', "en": 'closed (Catalan)'},
    {"es": 'parada', "en": 'stop (Catalan)'},
    {"es": 'adéu', "en": 'goodbye (Catalan)'},
    {"es": 'si us plau', "en": 'please (Catalan)'},
    {"es": 'gràcies', "en": 'thanks (Catalan)'},
    {"es": 'dilluns', "en": 'Monday (Catalan)'},
    {"es": 'dissabte', "en": 'Saturday (Catalan)'},
    {"es": 'reservar una mesa', "en": 'to book a table'},
    {"es": 'tramitar el papeleo', "en": 'to handle the paperwork'},
    {"es": 'alquilar un piso', "en": 'to rent a flat'},
    {"es": 'compartir gastos', "en": 'to share expenses'},
    {"es": 'apuntarse al gimnasio', "en": 'to sign up at the gym'},
    {"es": 'echar de menos', "en": 'to miss (someone)'},
    {"es": 'acostumbrarse a', "en": 'to get used to'},
    {"es": 'quedarse sin batería', "en": 'to run out of battery'},
    {"es": 'recargar el móvil', "en": 'to charge the phone'},
    {"es": 'perder el WiFi', "en": 'to lose the WiFi'},
    {"es": 'solicitar información', "en": 'to request information'},
    {"es": 'devolver el libro', "en": 'to return the book'},
    {"es": 'aprobar el examen', "en": 'to pass the exam'},
    {"es": 'suspender el examen', "en": 'to fail the exam'},
    {"es": 'entregar el trabajo', "en": 'to hand in the assignment'},
    {"es": 'hacer la colada', "en": 'to do the laundry'},
    {"es": 'fregar los platos', "en": 'to wash the dishes'},
    {"es": 'sacar la basura', "en": 'to take out the trash'},
    {"es": 'regatear el precio', "en": 'to bargain the price'},
    {"es": 'cambiar de opinión', "en": "to change one's mind"},
    {"es": 'la playa de la Barceloneta', "en": 'Barceloneta beach'},
    {"es": 'el Barrio Gótico', "en": 'the Gothic Quarter'},
    {"es": 'la Sagrada Familia', "en": 'the Sagrada Familia'},
    {"es": 'el Park Güell', "en": 'Park Güell'},
    {"es": 'la Rambla', "en": 'the Rambla'},
]

DAILY_SENTENCES_ES = [
    '¿Dónde está la estación de metro más cercana a la Plaça de Catalunya?',
    'Necesito comprar un abono de transporte para estudiar en Barcelona un semestre.',
    '¿A qué hora abre la biblioteca de la universidad los sábados?',
    'Quiero reservar una mesa en un restaurante cerca de la playa para el viernes.',
    '¿Cuánto cuesta el menú del día con bebida incluida?',
    'Me he perdido en el Barrio Gótico; ¿puede indicarme cómo llegar al metro?',
    'Tengo cita en el CAP mañana por la mañana para renovar la tarjeta sanitaria.',
    '¿Puedo pagar el alquiler del piso por transferencia bancaria?',
    'Busco un piso compartido cerca del campus con internet incluido.',
    '¿Qué documentos necesito para el empadronamiento en el ayuntamiento?',
    'El tren de Rodalies lleva veinte minutos de retraso por una incidencia.',
    '¿Hay alguna farmacia abierta ahora cerca de la Sagrada Familia?',
    'Quiero apuntarme a clases de catalán para entender las señales del metro.',
    '¿Cuál es la mejor línea de metro para ir del aeropuerto al centro?',
    'Hoy hace mucho calor; prefiero estudiar por la tarde en la biblioteca.',
    '¿Dónde puedo validar mi billete antes de subir al autobús?',
    'Necesito cambiar mi cita en la oficina de extranjería por un conflicto de horario.',
    '¿Este mercado municipal abre los domingos por la mañana?',
    'Voy a entregar el trabajo de la universidad antes del plazo de las cinco.',
    '¿Puedo llevar la maleta grande en el ascensor del metro?',
    'Quiero abrir una cuenta bancaria en España siendo estudiante extranjero.',
    '¿A qué hora empieza el concierto de La Mercè en el parque?',
    'El casero me ha pedido la fianza y el primer mes de alquiler por adelantado.',
    '¿Hay WiFi gratuito en la sala de estudio del campus?',
    'Necesito una copia del contrato de alquiler para tramitar la residencia.',
    '¿Dónde está la parada del aerobús en la terminal T1?',
    'Prefiero comprar fruta fresca en el mercado que en el supermercado.',
    '¿Cuánto tarda el visado de estudiante en estar listo?',
    'Me duele la garganta y quiero pedir cita con el médico de cabecera.',
    '¿Se puede pagar con tarjeta en la feria de Sant Jordi?',
    'Voy a tomar el cercanías hasta Sants y luego cambiar al metro.',
    '¿Qué barrio recomiendas para vivir si estudio en la Universidad de Barcelona?',
]

DAILY_PHRASES_ES = [
    'buenos días',
    'muchas gracias',
    'perdón, ¿me ayuda?',
    'un café con leche, por favor',
    'la cuenta, por favor',
    '¿Cuánto cuesta?',
    'no entiendo',
    '¿Puede repetir?',
    'más despacio, por favor',
    '¿Dónde está la salida?',
    'un billete de metro',
    'necesito ayuda',
    'estoy perdido',
    'tengo una reserva',
    'sin gluten, por favor',
    'para llevar',
    '¿Aceptan tarjeta?',
    '¿Hay WiFi?',
    'soy estudiante de intercambio',
    'hablo un poco de catalán',
    'hasta mañana',
    'nos vemos en clase',
    'qué bien',
    'qué pena',
    'en serio',
    'de acuerdo',
    'no pasa nada',
    '¡cuidado!',
    '¡felicidades!',
    'buen viaje',
    'buen provecho',
    '¡salud!',
]

READER_PASSAGES_SEED = [
    {
        "id": 'metro-bus',
        "lang": 'es',
        "title": 'Moverse en Barcelona: metro y bus',
        "body": (
            'Barcelona tiene una red de metro amplia y fácil de usar si conoces algunas reglas básicas. Antes de entrar, compra un billete o recarga tu tarjeta T-usual en las máquinas de la estación. Recuerda validar el billete en los lectores amarillos; si no lo haces, puedes recibir una multa. En hora punta los vagones van muy llenos, especialmente en las líneas que cruzan el centro. Los autobuses complementan el metro y llegan a barrios donde no hay estación cercana. Consulta la aplicación oficial para ver retrasos y obras. Si vienes del aeropuerto, el aerobús es cómodo aunque cuesta más que el metro. Pregunta siempre si hay transbordo y cuántas zonas cubre tu título de transporte. Con un poco de práctica, moverte por la ciudad se vuelve automático.'
        ),
        "en": (
            'Barcelona has a large metro network that is easy to use if you know a few basic rules. Before entering, buy a ticket or reload your T-usual card at the station machines. Remember to validate your ticket at the yellow readers; if you do not, you may receive a fine. At rush hour the carriages are very crowded, especially on lines that cross the center. Buses complement the metro and reach neighborhoods where there is no nearby station. Check the official app to see delays and works. If you come from the airport, the Aerobús is convenient although it costs more than the metro. Always ask if there is a transfer and how many zones your transport pass covers. With a little practice, getting around the city becomes automatic.'
        ),
    },
    {
        "id": 'boqueria',
        "lang": 'es',
        "title": 'La Boqueria y los mercados de la ciudad',
        "body": (
            'La Boqueria es uno de los mercados más famosos de Barcelona y un lugar perfecto para practicar español con los vendedores. Llega temprano si quieres evitar multitudes y encontrar pescado y fruta muy frescos. Muchos puestos muestran precios por kilo; observa la balanza y pregunta si no entiendes el peso. Es normal saludar con un «buenos días» antes de pedir. En otros barrios encontrarás mercados municipales más tranquilos y a menudo más baratos. Lleva una bolsa reutilizable y efectivo por si la tarjeta falla. Probar fruta de temporada es una forma divertida de conocer la cultura local. Después de comprar, puedes preparar una comida económica en tu piso compartido. Los mercados también enseñan vocabulario de cocina que te servirá en restaurantes y supermercados.'
        ),
        "en": (
            "La Boqueria is one of Barcelona's most famous markets and a perfect place to practice Spanish with vendors. Arrive early if you want to avoid crowds and find very fresh fish and fruit. Many stalls show prices per kilo; watch the scale and ask if you do not understand the weight. It is normal to greet with a «good morning» before ordering. In other neighborhoods you will find quieter municipal markets that are often cheaper. Bring a reusable bag and cash in case the card fails. Trying seasonal fruit is a fun way to learn local culture. After shopping, you can prepare an economical meal in your shared flat. Markets also teach kitchen vocabulary that will help you in restaurants and supermarkets."
        ),
    },
    {
        "id": 'universidad',
        "lang": 'es',
        "title": 'Estudiar en la universidad española',
        "body": (
            'El sistema universitario en España puede parecer distinto si vienes de otro país. Al inicio del semestre debes completar la matrícula y recoger tu carnet de estudiante. Los profesores suelen publicar materiales en plataformas digitales; revisa el calendario de exámenes desde el primer día. La asistencia no siempre es obligatoria, pero participar en clase mejora la nota final. Los trabajos en grupo son frecuentes; acuerda reuniones claras y reparte tareas por escrito. La biblioteca del campus es un refugio silencioso para estudiar, aunque en época de exámenes hay mucha presión. Si necesitas adaptaciones por idioma, pregunta en la secretaría académica. Las becas y el intercambio tienen plazos estrictos, así que organiza la documentación con antelación. Con organización y preguntas a compañeros locales, adaptarse al ritmo académico es totalmente posible.'
        ),
        "en": (
            'The university system in Spain may seem different if you come from another country. At the start of the semester you must complete enrollment and pick up your student ID. Professors usually publish materials on digital platforms; check the exam calendar from day one. Attendance is not always mandatory, but participating in class improves the final grade. Group projects are common; agree on clear meetings and divide tasks in writing. The campus library is a quiet refuge for studying, although during exam season there is a lot of pressure. If you need accommodations for language, ask at the academic office. Scholarships and exchange programs have strict deadlines, so organize paperwork in advance. With organization and questions to local classmates, adapting to the academic pace is entirely possible.'
        ),
    },
    {
        "id": 'alquilar-piso',
        "lang": 'es',
        "title": 'Alquilar un piso en Barcelona',
        "body": (
            'Encontrar piso en Barcelona requiere paciencia y documentación lista. Muchos estudiantes comparten piso para reducir gastos; pregunta qué incluye el alquiler: agua, internet, comunidad de vecinos. El casero puede pedir una fianza equivalente a uno o dos meses. Lee el contrato con calma y comprueba la duración, las visitas y las reglas sobre mascotas o fiestas. Las agencias inmobiliarias cobran honorarios; compara varias opciones antes de firmar. Visita el barrio de noche y de día para evaluar ruido y transporte. Guarda recibos de alquiler y facturas; te servirán para trámites administrativos. Si hay averías, comunícalo por escrito al casero. Empadronarte en la vivienda facilita muchos trámites oficiales. Un piso bien elegido hace que tu experiencia en la ciudad sea más estable y menos estresante.'
        ),
        "en": (
            'Finding a flat in Barcelona requires patience and ready documentation. Many students share a flat to reduce costs; ask what the rent includes: water, internet, building fees. The landlord may ask for a deposit equal to one or two months. Read the contract carefully and check duration, visits, and rules about pets or parties. Estate agencies charge fees; compare several options before signing. Visit the neighborhood at night and during the day to assess noise and transport. Keep rent receipts and bills; they will help with administrative procedures. If there are breakdowns, notify the landlord in writing. Registering your address at the flat facilitates many official procedures. A well-chosen flat makes your experience in the city more stable and less stressful.'
        ),
    },
    {
        "id": 'catalan',
        "lang": 'es',
        "title": 'Entender el catalán en la calle',
        "body": (
            'En Barcelona oirás catalán en carteles, anuncios del metro y conversaciones cotidianas. No necesitas hablarlo con fluidez para vivir bien, pero reconocer palabras básicas ayuda mucho. «Sortida» significa salida y «entrada» significa entrada; las verás en estaciones y edificios públicos. Mucha gente cambia al castellano si les hablas en español. En la universidad encontrarás documentos bilingües; pide una versión en castellano si lo necesitas. Aprender saludos en catalán es un gesto amable: «bon dia», «gràcies». Los medios locales mezclan ambos idiomas. No confundas el catalán con un dialecto «incorrecto»; es una lengua oficial con su propia cultura. Con el tiempo, las señales repetidas se vuelven familiares y reduces la sensación de estar perdido en la ciudad.'
        ),
        "en": (
            'In Barcelona you will hear Catalan on signs, metro announcements, and everyday conversations. You do not need to speak it fluently to live well, but recognizing basic words helps a lot. «Sortida» means exit and «entrada» means entrance; you will see them in stations and public buildings. Many people switch to Spanish if you speak to them in Spanish. At university you will find bilingual documents; ask for a Spanish version if you need it. Learning greetings in Catalan is a kind gesture: «bon dia», «gràcies». Local media mix both languages. Do not mistake Catalan for an «incorrect» dialect; it is an official language with its own culture. Over time, repeated signs become familiar and you reduce the feeling of being lost in the city.'
        ),
    },
    {
        "id": 'merce',
        "lang": 'es',
        "title": 'La Mercè: fiesta mayor de Barcelona',
        "body": (
            'La Mercè es la fiesta mayor de la ciudad y llena las calles de música, fuegos artificiales y actividades gratis. Suele celebrarse a finales de septiembre; consulta el programa con antelación porque hay cientos de eventos. Los conciertos en parques públicos son muy populares; llega pronto si quieres buen sitio. Algunas calles se cierran al tráfico; planifica tu ruta en metro o a pie. Es una oportunidad excelente para escuchar castellano y catalán en anuncios y presentaciones. Si no te gustan las multitudes, busca actividades en barrios alejados del centro. Ten cuidado con carteristas en zonas muy concurridas. Bebe agua y usa protección solar en eventos diurnos. Participar en La Mercè te conecta con la vida cultural real de Barcelona más allá de los monumentos turísticos.'
        ),
        "en": (
            "La Mercè is the city's main festival and fills the streets with music, fireworks, and free activities. It is usually celebrated at the end of September; check the program in advance because there are hundreds of events. Concerts in public parks are very popular; arrive early if you want a good spot. Some streets close to traffic; plan your route by metro or on foot. It is an excellent opportunity to hear Spanish and Catalan in announcements and presentations. If you do not like crowds, look for activities in neighborhoods away from the center. Be careful with pickpockets in very busy areas. Drink water and use sun protection at daytime events. Taking part in La Mercè connects you with Barcelona's real cultural life beyond tourist monuments."
        ),
    },
    {
        "id": 'sant-jordi',
        "lang": 'es',
        "title": 'Sant Jordi: libros y rosas',
        "body": (
            'El día de Sant Jordi, el 23 de abril, Barcelona se transforma con puestos de libros y rosas en las aceras. Es tradición regalar una rosa y un libro a familiares o pareja. Las Ramblas y el Passeig de Gràcia se llenan de gente, pero también hay librerías pequeñas en muchos barrios. Es un buen momento para practicar español pidiendo recomendaciones al librero. Algunas universidades organizan actividades culturales ese día. Lleva efectivo por si un puesto no acepta tarjeta. Si estudias literatura o historia, encontrarás ediciones especiales y firmas de autores. Aunque el día es festivo en el calendario cultural, las clases pueden continuar; revisa el horario del campus. Sant Jordi muestra cómo Cataluña mezcla tradición, lengua y vida pública de forma muy visible.'
        ),
        "en": (
            "On Sant Jordi's day, April 23, Barcelona transforms with book and rose stalls on the sidewalks. It is traditional to give a rose and a book to family or a partner. Las Ramblas and Passeig de Gràcia fill with people, but there are also small bookshops in many neighborhoods. It is a good time to practice Spanish by asking the bookseller for recommendations. Some universities organize cultural activities that day. Bring cash in case a stall does not accept cards. If you study literature or history, you will find special editions and author signings. Although the day is a cultural holiday, classes may continue; check the campus schedule. Sant Jordi shows how Catalonia mixes tradition, language, and public life in a very visible way."
        ),
    },
    {
        "id": 'salud-cap',
        "lang": 'es',
        "title": 'Salud pública: el CAP y la tarjeta sanitaria',
        "body": (
            'Como residente o estudiante en España conviene conocer el sistema de atención primaria. El CAP es el centro de salud de tu barrio donde atiende el médico de cabecera. Para pedir cita sueles usar la app o llamar por teléfono; en urgencias leves también hay visita sin cita. La tarjeta sanitaria identifica tu derecho a atención pública si cumples requisitos. Lleva documento de identidad y empadronamiento cuando tramites el alta. Las farmacias pueden orientarte sobre productos sin receta, pero no sustituyen una consulta seria. Si el profesor de la universidad habla de «baja médica», es el certificado de incapacidad temporal. Guarda informes y recetas en una carpeta digital. En temporada de gripe, los centros van saturados; sé paciente y llega con vocabulario básico de síntomas para explicar cómo te sientes.'
        ),
        "en": (
            'As a resident or student in Spain it is worth knowing the primary care system. The CAP is your neighborhood health center where the GP sees patients. To request an appointment you usually use the app or call by phone; for minor urgent issues there is also walk-in care. The health card identifies your right to public care if you meet requirements. Bring ID and municipal registration when you register. Pharmacies can guide you on over-the-counter products, but they do not replace a serious consultation. If a university professor mentions «sick leave», it is the temporary disability certificate. Keep reports and prescriptions in a digital folder. During flu season, centers are busy; be patient and arrive with basic symptom vocabulary to explain how you feel.'
        ),
    },
    {
        "id": 'banca',
        "lang": 'es',
        "title": 'Dinero y banca en España',
        "body": (
            'Abrir una cuenta bancaria facilita pagar el alquiler, recibir becas y evitar comisiones por retiradas. Los bancos suelen pedir pasaporte, NIE o TIE, empadronamiento y a veces un certificado de matrícula. Compara cuentas para estudiantes sin comisiones de mantenimiento. Bizum es muy popular para pagos entre personas; te pedirán vincular el móvil. En muchos comercios puedes pagar con tarjeta, pero en mercados pequeños conviene llevar efectivo. Revisa el tipo de cambio si recibes dinero del extranjero. Guarda los comprobantes de transferencias al casero. Si pierdes la tarjeta, bloquéala desde la app inmediatamente. Aprender vocabulario de finanzas — recibo, deuda, ingreso — te ayuda en trámites universitarios y de alquiler.'
        ),
        "en": (
            'Opening a bank account makes it easier to pay rent, receive scholarships, and avoid withdrawal fees. Banks usually ask for passport, NIE or TIE, municipal registration, and sometimes an enrollment certificate. Compare student accounts with no maintenance fees. Bizum is very popular for payments between people; they will ask you to link your phone. In many shops you can pay by card, but in small markets it is wise to carry cash. Check the exchange rate if you receive money from abroad. Keep transfer receipts for the landlord. If you lose your card, block it from the app immediately. Learning finance vocabulary — receipt, debt, income — helps with university and rental procedures.'
        ),
    },
    {
        "id": 'renfe-rodalies',
        "lang": 'es',
        "title": 'Renfe y Rodalies: trenes de cercanías',
        "body": (
            'Además del metro, muchos estudiantes usan Rodalies para ir a Sants, el campus en Bellaterra o pueblos de la costa. Compra el billete en máquinas o apps indicando origen y destino; conserva el ticket hasta salir. En hora punta los andenes están llenos; espera detrás de la línea amarilla. Los retrasos se anuncian en pantallas; aprende palabras como «incidencia» y «cancelación». Si tienes abono multizona, verifica que cubre el trayecto que haces cada día. Las conexiones con metro suelen pasan por estaciones grandes; sigue señales de transbordo. Para excursiones de fin de semana, reserva con antelación en trenes regionales. Lleva auriculares pero mantén atención a anuncios por si cambia el andén. Dominar cercanías amplía dónde puedes vivir y estudiar sin depender solo del metro urbano.'
        ),
        "en": (
            'Besides the metro, many students use Rodalies to go to Sants, the campus in Bellaterra, or coastal towns. Buy your ticket at machines or apps indicating origin and destination; keep the ticket until you exit. At rush hour platforms are crowded; wait behind the yellow line. Delays are announced on screens; learn words like «incident» and «cancellation». If you have a multi-zone pass, check that it covers the trip you make each day. Connections with the metro usually go through large stations; follow transfer signs. For weekend trips, book regional trains in advance. Bring headphones but pay attention to announcements in case the platform changes. Mastering commuter trains expands where you can live and study without relying only on the urban metro.'
        ),
    },
    {
        "id": 'barrios',
        "lang": 'es',
        "title": 'Barrios de Barcelona para vivir y estudiar',
        "body": (
            'Elegir barrio influye en precio, ambiente y tiempo de transporte. Gràcia es popular entre estudiantes por sus plazas y bares, pero el alquiler sube cada año. Poble-sec y Sant Antoni ofrecen buena conexión al centro y mercados locales. Eixample tiene calles amplias y muchas líneas de metro, ideal si valoras luz natural. Poblenou combina playa cercana y espacios de coworking. Horta y Nou Barris suelen ser más económicos, con más trayecto hasta el campus. Visita varios pisos antes de decidir; fotos online no muestran ruido nocturno. Pregunta a vecinos sobre seguridad y limpieza en la calle. Conocer tu barrio — panadería, farmacia, supermercado — hace la vida diaria más cómoda y te da contexto real para practicar español fuera de clase.'
        ),
        "en": (
            'Choosing a neighborhood affects price, atmosphere, and commute time. Gràcia is popular among students for its squares and bars, but rent rises every year. Poble-sec and Sant Antoni offer good connections to the center and local markets. Eixample has wide streets and many metro lines, ideal if you value natural light. Poblenou combines nearby beach and coworking spaces. Horta and Nou Barris are usually more economical, with a longer trip to campus. Visit several flats before deciding; online photos do not show night noise. Ask neighbors about safety and street cleanliness. Knowing your neighborhood — bakery, pharmacy, supermarket — makes daily life more comfortable and gives you real context to practice Spanish outside class.'
        ),
    },
    {
        "id": 'empadronamiento',
        "lang": 'es',
        "title": 'Empadronamiento y trámites en el ayuntamiento',
        "body": (
            'El empadronamiento registra dónde vives y es clave para muchos trámites en Barcelona. Necesitas contrato de alquiler o autorización del casero, pasaporte y a veces cita previa online. En la oficina municipal te darán un certificado que sirve para sanidad, banco o becas. Si cambias de piso, debes actualizar el empadronamiento en plazo. Sin este paso, otros procesos como el NIE o la tarjeta sanitaria se complican. Lleva copias impresas y originales; las normas pueden cambiar según tu situación migratoria. Pide cita en horario de mañana para evitar colas largas. El personal atiende en castellano y a menudo en catalán; prepara frases simples para explicar tu caso. Organizar papeles desde el primer mes te ahorra estrés cuando la universidad o el trabajo pidan certificados oficiales.'
        ),
        "en": (
            'Municipal registration records where you live and is key for many procedures in Barcelona. You need a rental contract or landlord authorization, passport, and sometimes an online appointment. At the municipal office you will receive a certificate useful for healthcare, banking, or scholarships. If you move, you must update registration on time. Without this step, other processes such as NIE or health card become complicated. Bring printed and original copies; rules may change depending on your immigration status. Book a morning appointment to avoid long queues. Staff serve in Spanish and often in Catalan; prepare simple phrases to explain your case. Organizing paperwork from the first month saves stress when university or work ask for official certificates.'
        ),
    },
]
